version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nlw-return
    volumes:
      - .PostgreSQL:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
